/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.crypto;

import javax.swing.JButton;
import javax.swing.JTextArea;

/**
 *
 * @author user
 */
public class FrameCrypto extends javax.swing.JFrame {

    /**
     * Creates new form FrameCrypto
     */
    public FrameCrypto() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaInput = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaOutput = new javax.swing.JTextArea();
        btnZakodirivat = new javax.swing.JButton();
        btnRazkodirovat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Крипто");

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ввод текста");

        areaInput.setColumns(20);
        areaInput.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        areaInput.setForeground(new java.awt.Color(0, 0, 0));
        areaInput.setLineWrap(true);
        areaInput.setRows(5);
        jScrollPane1.setViewportView(areaInput);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Закодированное сообщение");

        areaOutput.setBackground(new java.awt.Color(255, 204, 204));
        areaOutput.setColumns(20);
        areaOutput.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        areaOutput.setForeground(new java.awt.Color(0, 0, 204));
        areaOutput.setLineWrap(true);
        areaOutput.setRows(5);
        jScrollPane2.setViewportView(areaOutput);

        btnZakodirivat.setBackground(new java.awt.Color(51, 204, 0));
        btnZakodirivat.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnZakodirivat.setForeground(new java.awt.Color(0, 0, 0));
        btnZakodirivat.setText("ЗАКОДИРОВАТЬ");

        btnRazkodirovat.setBackground(new java.awt.Color(255, 204, 102));
        btnRazkodirovat.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnRazkodirovat.setForeground(new java.awt.Color(0, 0, 0));
        btnRazkodirovat.setText("РАЗКОДИРОВАТЬ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnZakodirivat, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)))
                        .addGap(180, 180, 180)
                        .addComponent(btnRazkodirovat, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 172, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnZakodirivat)
                    .addComponent(btnRazkodirovat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCrypto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCrypto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCrypto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCrypto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCrypto().setVisible(true);
            }
        });
    }

    public JButton getBtnRazkodirovat() {
        return btnRazkodirovat;
    }

    public JButton getBtnZakodirivat() {
        return btnZakodirivat;
    }

    public JTextArea getAreaInput() {
        return areaInput;
    }

    public void setAreaInput(JTextArea areaInput) {
        this.areaInput = areaInput;
    }

    public JTextArea getAreaOutput() {
        return areaOutput;
    }

    public void setAreaOutput(JTextArea reaOutput) {
        this.areaOutput = reaOutput;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaInput;
    private javax.swing.JTextArea areaOutput;
    private javax.swing.JButton btnRazkodirovat;
    private javax.swing.JButton btnZakodirivat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
